// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ContactTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void contactTest() {
    driver.get("https://www.nexchar.com/");
    driver.manage().window().setSize(new Dimension(1936, 1048));
    driver.findElement(By.cssSelector(".nav-item:nth-child(6) .nav-link-title")).click();
    driver.findElement(By.id("FullName")).click();
    driver.findElement(By.id("FullName")).sendKeys("New User ");
    driver.findElement(By.id("Email")).click();
    driver.findElement(By.id("Email")).sendKeys("new@gmail.com");
    driver.findElement(By.id("Query")).click();
    {
      WebElement dropdown = driver.findElement(By.id("Query"));
      dropdown.findElement(By.xpath("//option[. = 'Request a demo']")).click();
    }
    driver.findElement(By.id("Message")).click();
    driver.findElement(By.id("Message")).sendKeys("demo data test ");
    driver.findElement(By.id("DNTCaptchaInputText")).click();
    driver.findElement(By.id("DNTCaptchaInputText")).sendKeys("4876");
    driver.findElement(By.cssSelector(".btn-primary")).click();
  }
}
